const productCatalog = [
  { id: 1, name: 'Oversized Cotton Shirt', description: 'A relaxed cotton shirt with an easy drape for everyday layering.', category: 'clothing', brand: 'Atelier North', color: 'White', theme: 'Everyday Essentials', price: 59, image: 'https://images.unsplash.com/photo-1603252110481-7ba873bf42ab', isNew: true },
  { id: 2, name: 'Minimal Blazer', description: 'A clean-lined blazer that brings a polished finish to daily outfits.', category: 'clothing', brand: 'Form & Field', color: 'Black', theme: 'Modern Tailoring', price: 129, image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35', isNew: true },
  { id: 3, name: 'Relaxed Trousers', description: 'Comfortable tailored trousers with a modern, relaxed silhouette.', category: 'clothing', brand: 'Form & Field', color: 'Beige', theme: 'Modern Tailoring', price: 79, image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80', isNew: true },
  { id: 4, name: 'Classic Leather Bag', description: 'A timeless leather bag designed to carry your everyday essentials.', category: 'accessories', brand: 'Common Ground', color: 'Brown', theme: 'Everyday Essentials', price: 149, image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3', isNew: true },
  { id: 5, name: 'Classic Wool Coat', description: 'A refined wool coat that adds warmth through cooler seasons.', category: 'clothing', brand: 'Atelier North', color: 'Camel', theme: 'Cold Weather', price: 189, image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a', isNew: true },
  { id: 6, name: 'Slim Fit Denim Jeans', description: 'Versatile slim-fit denim made for easy everyday styling.', category: 'clothing', brand: 'Common Ground', color: 'Blue', theme: 'Weekend Casual', price: 89, image: 'https://images.unsplash.com/photo-1542272604-787c3835535d', isNew: true },
  { id: 7, name: 'Premium Knit Sweater', description: 'A soft knit sweater with a versatile shape for layering.', category: 'clothing', brand: 'Atelier North', color: 'Cream', theme: 'Cold Weather', price: 99, image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27', isNew: true },
  { id: 8, name: 'Leather Crossbody Bag', description: 'A compact crossbody bag for keeping daily essentials close.', category: 'accessories', brand: 'Common Ground', color: 'Black', theme: 'Everyday Essentials', price: 119, image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c', isNew: true },
  { id: 9, name: 'Premium Cotton Shirt', description: 'A breathable cotton shirt with a crisp finish and all-day comfort.', category: 'clothing', brand: 'Atelier North', color: 'Blue', theme: 'Everyday Essentials', price: 69, image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c', isNew: true },
  { id: 10, name: 'Relaxed Fit Blazer', description: 'An easy-fitting blazer that balances comfort with sharp tailoring.', category: 'clothing', brand: 'Form & Field', color: 'Navy', theme: 'Modern Tailoring', price: 139, image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf' },
  { id: 11, name: 'Straight Leg Trousers', description: 'Straight-leg trousers with a versatile cut for work or weekends.', category: 'clothing', brand: 'Form & Field', color: 'Black', theme: 'Modern Tailoring', price: 89, image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f' },
  { id: 12, name: 'Leather Shoulder Bag', description: 'A structured shoulder bag with room for everyday essentials.', category: 'accessories', brand: 'Common Ground', color: 'Tan', theme: 'Everyday Essentials', price: 159, image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa' },
  { id: 13, name: 'Classic Wool Coat', description: 'A warm wool outer layer with a timeless, easy-to-style silhouette.', category: 'clothing', brand: 'Atelier North', color: 'Charcoal', theme: 'Cold Weather', price: 189, image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a' },
  { id: 21, name: 'Classic Cotton Shirt', description: 'A wardrobe staple in soft cotton with a timeless everyday fit.', category: 'clothing', brand: 'Atelier North', color: 'White', theme: 'Everyday Essentials', price: 69, image: 'https://images.unsplash.com/photo-1603252110481-7ba873bf42ab' },
  { id: 22, name: 'Minimal Blazer', description: 'A versatile tailored layer with understated modern details.', category: 'clothing', brand: 'Form & Field', color: 'Charcoal', theme: 'Modern Tailoring', price: 129, image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35' },
  { id: 23, name: 'Relaxed Trousers', description: 'Lightly tailored trousers designed for comfort and movement.', category: 'clothing', brand: 'Form & Field', color: 'Olive', theme: 'Modern Tailoring', price: 79, image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80' },
  { id: 24, name: 'Premium Knit Sweater', description: 'A premium-feel knit that pairs easily with your everyday wardrobe.', category: 'clothing', brand: 'Atelier North', color: 'Rust', theme: 'Cold Weather', price: 99, image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27' },
  { id: 25, name: 'Slim Fit Denim', description: 'Classic denim with a streamlined fit for effortless daily wear.', category: 'clothing', brand: 'Common Ground', color: 'Indigo', theme: 'Weekend Casual', price: 89, image: 'https://images.unsplash.com/photo-1542272604-787c3835535d' },
  { id: 26, name: 'Leather Crossbody', description: 'A hands-free leather bag with a clean, compact design.', category: 'accessories', brand: 'Common Ground', color: 'Burgundy', theme: 'Everyday Essentials', price: 119, image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c' },
  { id: 27, name: 'Classic Wool Coat', description: 'A timeless outerwear piece made for cool-weather layering.', category: 'clothing', brand: 'Atelier North', color: 'Camel', theme: 'Cold Weather', price: 189, image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a' },
  { id: 28, name: 'Oversized Hoodie', description: 'A soft oversized hoodie for relaxed days and easy layering.', category: 'clothing', brand: 'Common Ground', color: 'Grey', theme: 'Weekend Casual', price: 89, image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7' },
  { id: 29, name: 'Leather Shoulder Bag', description: 'An everyday shoulder bag with a polished leather look.', category: 'accessories', brand: 'Common Ground', color: 'Black', theme: 'Everyday Essentials', price: 149, image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3' },
];

const selectProducts = (ids) => {
  const productsById = new Map(productCatalog.map((product) => [product.id, product]));
  return ids.map((id) => productsById.get(id));
};

export const products = productCatalog;
export const newArrivalProducts = selectProducts([1, 2, 3, 4, 5, 6, 7, 8]);
export const bestSellerProducts = selectProducts([9, 10, 11, 12, 13]);
export const featuredProducts = selectProducts([21, 22, 23, 24, 25, 26, 27, 28, 29]);
